/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}', './index.html'],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      screens: {
        xs: '375px',
        smH: { raw: '(max-height: 720px)' },
      },
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        backgroundPopup: '#0A0912E5',
        start: '#ffbb00',
        middle: '#FFA445',
        end: '#FF3C78',
        btnStart: '#ffd500',
        txtStart: '#ffb800',
        txtMiddle: '#ff972b',
        gold: '#FFD94A',
        silver: '#D7D8C8',
        bronze: '#F2AA69',
        popup: '#242137',
        poolBorder: '#22202f',
        pool: '#13121c',
        description: '#BFBDD0',
        tabActive: '#2E2F7F',
        tab: '#100f24',
        freebies: '#FDFDFD',
        claim: '#282829',
        bgFreebies: '#12274E',
        countdown: '#F0F2FA',
        gameDescription: '#FCFCFC',
        describe: '#FCFCFC',
        session: '#0F0F0F',
        gameDetail: '#091428',
        bgBeginner: '#01ffff',
        bgAdvanced: '#f6b26b',
        bgIntermediate: '#ffff01',
        bgFriend: '#081325',
        bgClaim: '#19BFEF',
        bgGray: '#B2B2B2',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      backgroundImage: {
        gradient: 'linear-gradient(274.59deg, #19bfef -11.3%, #0dc9ec 50.13%, #00e3d0 111.55%)',
        primaryGradient: 'linear-gradient(to right, rgba(0, 227, 208, 1) 0%, rgba(13, 201, 235, 1) 100%)',
        grayGradient: 'linear-gradient(to right, rgba(53, 74, 87, 1) 0%, rgba(41, 46, 73, 1) 100%)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '3xl': 'calc(var(--radius) * 2)',
        '3.5xl': '20px',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      width: {
        120: '120px',
        90: '90px',
        91: '91px',
        60: '60px',
      },
      height: {
        82: '82px',
        90: '90px',
        60: '60px',
      },
      fontSize: {
        13: '13px',
        22: '22px',
        40: '40px',
        28: '28px',
      },
      lineHeight: {
        heading: '1.2',
      },
    },
    fontSize: {
      xs: ['0.75rem', { lineHeight: '1.4' }],
      sm: ['0.875rem', { lineHeight: '1.4' }],
      15: ['0.9375rem', { lineHeight: '1.4' }],
      base: ['0.9375rem', { lineHeight: '1.2' }],
      lg: ['1.125rem', { lineHeight: '1.4' }],
      xl: ['1.25rem', { lineHeight: '1.2' }],
      '2xl': ['1.5rem', { lineHeight: '1.2' }],
      '3xl': ['1.75rem', { lineHeight: '1.2' }],
      '4xl': ['2rem', { lineHeight: '1.2' }],
      '5xl': ['2.5rem', { lineHeight: '1.2' }],
      '6xl': ['3.75rem', { lineHeight: '1' }],
      '7xl': ['4.5rem', { lineHeight: '1' }],
      '8xl': ['6rem', { lineHeight: '1' }],
      '9xl': ['8rem', { lineHeight: '1' }],
    },
  },
  plugins: [require('tailwindcss-animate')],
};
